apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-color
  name: webapp-color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-color
  template:
    metadata:
      labels:
        app: webapp-color
    spec:
      containers:
        - name: webapp-color
          image: gcr.io/aamoyel/webapp-color:v0.1.0
          env:
            - name: APP_COLOR
              value: "blue"
          ports:
            - name: http
              containerPort: 8080
